# Site settings
title: Scholar
header-img: img/favicon.ico
email: toko.dougherty@gmail.com
copyright_name: Toko Dougherty
description: "Rebel to the system, cause the system sucks."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: toko.dougherty
github_username:  heinrici
facebook_username:  Toko Dougherty
email_username:  toko.dougherty@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
